# 서론 {#introduction}

## 배경 및 목적
의약품의 유효성 및 안전성은 ‘의약품 임상시험 관리기준’(「의약품 등의 안전에 관한 규칙」[별표4])에 따른 임상시험으로 입증하며, 이러한 기준을 따르는 임상 시험의 계획과 분석에서 통계의 역할은 필수적이다. 본 가이드라인은 임상시험에 적용되는 통계학적 방법의 원칙들을 통일하기 위한 것으로 임상시험 개발 전반에서 임상시험의 설계, 수행, 분석, 평가의 방향성을 제시하고, 품목허가를 위한 제출 자료 작성 및 의약품의 안전성 및 유효성을 평가하는 데 도움을 주고자 한다.

본 가이드라인은 ICH(International Conference on Harmonisation)가 1998년 2월 5일 Step 4에 상정한 임상시험의 통계적 원칙(E9)에 근거하여 작성되었다.

## 범위 및 방향
임상시험의 계획, 수행 및 통계학적 분석에 관한 세부사항은 임상시험계획서에 명확하고 구체적으로 기술한다. 임상시험계획서에 기술된 대로 임상시험을 진행하는 것과 주요 결과 변수에 대한 분석에 관하여 임상시험계획서에 얼마나 잘 기술되었느냐에 따라 임상시험의 최종 결론에 대한 신뢰성이 영향을 받는다.

확증시험(confirmatory trials)은 일차변수로 유효성 외에 안전성 변수(예를 들어 유해사례, 임상검사치 또는 심전도 측정), 약동학 또는 약력학적 변수(생물학적 동등성 확증시험)를 포함할 수 있다. 이 가이드라인에서 제안한 원칙들은 여러 임상시험의 통합 자료로부터 도출되는 확증적 결과 및 주로 탐색시험에 해당하는 초기 의약품 개발단계의 임상시험에도 적용될 수 있다.

이 가이드라인에서 제안한 원칙들의 대부분은 비뚤림(bias)을 최소화하고 정밀도를 최대화하기 위한 것이다. ‘비뚤림’이란 임상시험의 계획, 수행, 분석 그리고 결과 해석 등의 과정에서 치료 효과의 추정치를 참값에서 벗어나게 만드는 요소들의 계통적인 경향성을 말한다(용어해설 참조). 비뚤림을 작게 하기 위해서는 잠재적 요인을 파악하는 것이 중요하다. 비뚤림은 임상시험으로부터 타당한 결론을 도출하는 과정에 큰 영향을 미칠 수 있다. 비뚤림은 치료군의 배정과 같은 임상시험의 설계 과정 (예: 위험성이 낮은 임상시험대상자들이 한 쪽의 치료에만 몰려서 배정되는 경우) 또는 임상시험 시행이나 분석 과정 (예: 임상시험계획서 위반 사항이나 임상시험 결과 등을 미리 알고서 해당 임상시험대상자를 결과 분석에서 제외시키는 경우) 중 치료 효과의 정확한 평가에 영향을 주는 비뚤림이 발생할 수 있다. 비뚤림은 잘 드러나지 않고, 직접적으로 그 효과를 측정할 수 없는 경우가 많으므로 임상시험의 결과와 주요 결론에 대한 견실성(robustness)을 평가하는 것이 중요하다. 견실성은 가정이 달라지거나 다른 방법으로 자료를 분석하더라도 임상시험의 치료 효과에 대한 주요 결론이 크게 달라지지 않는 것을 의미한다. 임상시험의 결과에서 제시되는 통계적 수치들에 대한 해석을 할 때에는 p- 값, 신뢰구간, 추론에 미치는 비뚤림의 잠재적 영향을 고려한다.

임상시험의 설계 및 분석의 주된 방법은 ‘확률 통계적 방법(Frequentist, 용어 해설 참조)’을 기반으로 하기 때문에 이 가이드라인은 가설검정 또는 신뢰구간 등을 말할 때 가장 많이 사용되는 방법을 주로 언급하였다. 그러나 이것은 다른 접근 방법이 적절하지 않다는 것을 의미하는 것은 아니며, 사유가 명확하고 최종 결론이 충분히 견실성이 있는 경우에는 베이지안(Baysian, 용어해설 참조) 방법 또는 다른 접근 방법들도 고려할 수 있다.

