# 임상시험 시 고려사항 {#trial}

## 임상시험 모니터링과 중간 분석
임상시험계획서에 따라 임상시험을 신중하게 수행함으로써 임상시험 결과의
신뢰성을 현저히 향상시킬 수 있다. 임상시험 중에 문제점을 조기에 발견하고
재발을 최소화할 수 있도록 모니터링을 적절히 시행한다.
확증시험의 모니터링은 두 종류가 있다. 한 종류는 임상시험의 질적 수준을
높게 유지하도록 감독하는 것이고 다른 하나는 이중 눈가림법을 해제하고 각
치료군을 비교하는 중간분석이다. 두가지 모니터링 모두 임상시험 관련자들에게
각각 다른 종류의 책임이 부과되고 다른 형태의 임상시험자료와 정보에 접근할
수 있으므로, 잠재적인 통계적 비뚤림과 실행적 비뚤림을 통제하기 위하여 각기
다른 종류의 원칙이 적용될 수 있다.
임상시험의 질적 수준을 감독하는 목적으로서의 첫번째 형태의 모니터링은
계획서의 준수여부, 수행된 임상시험자료가 믿을만한지, 계획된 시험대상자 확보율이
달성되었는지, 임상시험 설계시 적용한 가설은 적절했었는지, 환자가 임상시험에
계속 참여할 수 있도록 하였는지 등을 점검한다(4.2 ～ 4.4절 참조). 이 방법은
치료효과 비교 시 필요한 정보에 접근하지 않아도 되고, 또한 눈가림을 해제하지
않아도 되므로, 제 1종 오류에 영향을 미치지 않는다. 이러한 목적으로 모니터링을
실시하는 것은 임상시험의뢰자의 책임이고, 임상시험의뢰자 또는 임상시험의뢰자가
선정한 독립적인 단체가 수행한다. 이런 형태의 모니터링 기간은 보통 임상시험
기관 선정에서부터 시작하여 마지막 임상시험대상자의 자료를 수집하고 정리할
때까지이다.
다른 임상시험 모니터링(중간분석)은 치료효과를 비교하는 것을 포함한다.
중간 분석은 눈가림을 해제한 상태에서의 치료군 배정(실제 치료 배정과 치료군의
배정)과 비교 치료군에 대한 요약 자료들을 알아야 한다. 이것은 사전(중간분석이
이루어지기 이전)에 미리 임상시험계획서에 포함되어 있어야 하고, 이로 인한
비뚤림이 생기지 않도록 주의하여야 한다.

## 선정기준 및 제외기준의 변경
임상시험계획서에서 정의된 선정 및 제외기준은 임상시험대상자 모집기간 동안
구체적으로 표현되고 일정하게 유지한다. 그러나 변경을 해야만 하는 경우도 있다.
예를 들어 장기간의 임상시험에서는 임상시험의 외부 또는 중간분석으로부터 얻은
의학적 지식에 의해 임상시험대상자 선정 및 제외기준이 변경될 수도 있다. 또한
모니터요원에 의해 임상시험대상자를 등록하여 선정하는 과정에서 반복적으로
발생하는 위반사항(violation)이 발견되거나 지나치게 엄격한 기준에 의해 임상
시험대상자 확보율이 대단히 낮을 경우에는 변경되기도 한다. 그러나 임상시험
대상자 선정 및 제외기준의 변경은 눈가림법을 유지하면서 진행되어야 하고
변경된 임상시험계획서 안에 상세히 서술한다. 변경된 임상시험 계획서에는 효과
추정치의 변경으로 시험대상자 수의 보정, 변경된 선정기준에 따른 층화분석 같은
분석계획의 변경 등을 포함한다.

## 임상시험대상자 확보율
환자를 장기간에 걸쳐 모집해야 하는 임상시험의 경우 임상시험대상자 확보율을
모니터한다. 만약 계획보다 눈에 띄게 떨어질 경우에는 임상시험의 검정력을
유지하고 선택 비뚤림이나 임상시험의 질적 수준을 저하시킬 수 있는 다른 요소를
제거하기 위해 그 원인을 밝히고 적절한 조치를 취한다. 다기관 임상시험에서는
이런 고려들이 기관별로 적용되어야 한다.

## 목표한 시험대상자 수 조정
장기간의 임상시험에서는 대개 원래의 계획과 시험대상자 수 산출의 근거가
되었던 가정을 점검해 볼 수 있다. 이것은 임상시험이 잠정적이고 불확실한
정보에 기초하여 계획된 경우에 특히 중요하다. 눈가림 상태에서의 자료에 대한
중간점검은 전체적인 반응의 변이양상이나 결과발생률 혹은 생존률 등이 기대했던
것과는 다르다는 것을 밝힐 수도 있다. 이런 경우 적절히 변경된 가정에 기초하여
시험대상자 수를 다시 산출할 수 있고, 이 내용을 반드시 변경된 임상시험계획서와
임상시험보고서에 그 근거를 설명하고 기록으로 남긴다. 제1종 오류와 신뢰구간에
대하여 눈가림 상태와 그 이후의 과정을 유지하기 위하여 취해지는 조치가 있다면
이를 설명한다.

## 중간분석 및 조기 종료
중간분석(용어해설 참조)은 공식적으로 임상시험을 종료하기 전의 어떤 시점
에서나 유효성 및 안전성에 대해 치료군간의 차이를 비교할 목적으로 실시하는
분석이다. 이러한 중간분석의 횟수나 방법, 결과가 임상시험의 해석에 영향을
미치므로 모든 중간분석은 미리 신중하게 계획되고 임상시험계획서 내에 기술한다.
특별한 상황에 의해 사전에 계획되어 있지 않던 중간분석이 필요하기도 한다.
이런 경우에는 치료효과를 비교할 자료에 대한 눈가림상태를 해제하기 이전에
임상시험계획서를 변경한다. 임상시험 종료여부를 결정할 의도로 중간분석을
계획한 경우에는 통계적 모니터링 계획에 따른 집단 축차 설계를 사용할 수 있다
(3.4절 참조). 이러한 중간분석의 목적은 연구대상이 되는 치료의 우월성이 확실
하거나, 유의한 치료효과의 차이가 나타날 것 같지 않는 경우, 받아들일 수 없을
정도로 명백한 부작용이 있는 경우 임상시험을 조기 종료하기 위한 것이다.
일반적으로 임상시험을 조기에 종료하고자 할 때 유효성으로 결정하는 경우
안전성으로 결정하는 경우보다 더 보수적인 접근이 필요하다. 임상시험의 계획
및 자료에 대한 모니터링과정에서 다수의 최종평가변수(multiple endpoints)를
다루었다면 다중성도 고려할 필요가 있다.
임상시험계획서에는 중간분석 일정을 기술하고 그렇지 않은 경우, 최소한 제
1종 오류의 수준을 유동적으로 적용하는 방법이 사용된다는 식의 중간분석이
사용될 가능성을 기술한다. 첫 번째 중간 분석 전에 임상시험계획서 변경을
통하여 보다 자세한 내용을 기술할 수도 있다. 종료기준과 구체적인 방법은
임상시험계획서나 그 변경 시 명확하게 기술한다. 이러한 내용은 서면화하거나
자료 모니터 위원회(Data Monitoring Committee)의 승인을 얻어야 한다(4.6절
참조). 계획된 분석 절차를 지키지 않았을 경우 임상시험 결과의 신뢰도가 저하될
수 있다. 임상시험계획을 변경할 필요가 있는 경우는 가능한 빨리 변경계획서
안에 그에 따라 바뀌게 될 통계분석방법의 변경을 구체화하고 특히 이러한 변경이
초래할 분석에 대한 영향과 결론을 논의한다. 변경된 방법을 적용함으로써 전체
제 1종 오류의 수준을 일정하게 통제할 수 있어야 한다.
중간분석으로 자료와 그 결과의 눈가림이 해제될 수 있으므로 중간분석은
철저히 기밀로 진행한다. 임상시험 관련자들이 분석 결과를 알게 되면 임상시험에
임하는 태도가 변할 수 있고, 임상시험대상자를 모집하는 과정이나 치료효과를
비교하는 과정에서 비뚤림이 초래될 수 있기 때문에 분석 결과에 대해서는 눈가림
상태를 유지한다. 이러한 원칙은 직접 중간분석을 실시하는 사람들을 제외하고는,
의뢰자에 의해 고용된 임상시험담당자나 직원들, 연구진등 임상시험대상자와
접촉하는 모든 사람들에게 적용한다. 연구자에게는 임상시험의 지속여부에 대한
결정과 임상시험 절차의 변경에 대해서만 알린다.
시험약의 유효성 및 안전성을 확인하고자 하는 대부분의 임상시험은 목표한
시험대상자 수를 다 완료할 때까지 진행한다. 즉 임상시험은 윤리적인 문제가
발생하거나, 더 이상의 환자를 등록하더라도 의도한 검정력을 확보하기 어려울
경우에만 조기 종료한다. 그러나 어떤 경우에는 다른 임상시험을 계획하여야 하는
등의 다양한 이유로 의뢰자가 임상시험 중간분석 결과에 미리 접근할 수도 있다.
또 다른 경우에는 일부의 임상시험에서만 윤리적인 이유로 치료 효과의 비교에
대한 검토가 필요할 수도 있다(생명에 위협을 주는 중대한 결과나 사망에 대한
연구). 어떤 경우든지 중간분석 계획은 치료효과를 비교하기 위한 자료에 대하여
눈가립법을 해제한 접근을 시도하기 이전에 발생할 수 있는 통계적, 실행적
비뚤림을 통제하기 위하여 임상시험계획서나 변경계획서에 기록한다.
대부분의 임상시험, 특히 공중 보건에 큰 의미를 갖는 임상시험의 경우에는
유효성 및 안전성 결과의 모니터에 대한 책임은 권한이 명확히 정해져 있는 독
립적인 자료 모니터링 위원회(Independent Data Monitoring Committee,
IDMC), 자료 및 안전성 모니터링 위원회(Data and Safety Monitoring Board)
혹은 자료 모니터링 위원회(Data Monitoring Committee)라 불리는 독립적인 위
원회에 부여한다.
의뢰자가 유효성 및 안전성 자료에 대한 모니터 역할을 함으로써 눈가림이
해제된 자료에 접근하려고 한다면 임상시험의 무결성을 유지하고 정보를 공유하는
것을 적절히 통제하고 제한하기 위하여 특별한 주의가 요망된다. 의뢰자는 내부
모니터링 위원회가 문서화된 표준작업지침서(Standard Operating Procedure)를
준수하였고 중간분석결과를 포함한 중요한 의사결정회의의 회의록이 유지되었다는
것을 보증하고 문서화 한다.
임상시험의 조기종료 유무에 관계없이 적절하게 계획되지 않은 중간분석은 임상
시험의 결과를 비뚤리게 하거나, 도출된 결론에 대한 신뢰를 약화시킬 수 있으므로
그러한 분석은 반드시 피한다. 계획되지 않은 중간분석을 실시하는 경우, 임상시험
결과보고서에 이유와 눈가림이 어느 정도 해제되었는지를 설명하고 발생할 수
있는 비뚤림의 잠재적인 크기 및 결과 해석에 미치는 영향을 평가하여야 한다.

## 독립적 자료 모니터링 위원회의 역할
임상시험의뢰자는 임상시험의 진행, 안전성 자료, 주요 유효성 변수를 주기적으로
평가하고, 임상시험의 지속, 변경 또는 종료에 대해 자문을 얻기 위해 독립적 자료
모니터링 위원회(용어해설 참조)를 구성할 수 있다. 독립적 자료 모니터링 위원회는
문서화된 표준작업지침을 구비하고, 중간분석 결과를 포함한 모든 회의 기록을
보존한다. 이 문서들은 임상시험 완료한 후에 검토할 수 있다. 중요한 비교 정보가
노출되는 것을 조정하고 임상시험 정보가 노출됨으로써 발생할 수 있는 역효과
로부터 임상시험의 무결성을 보호하기 위해서 독립적 자료 모니터링 위원회의
독립성이 보장되어야 한다. 독립 자료 모니터링 위원회는 임상시험심사위원회
또는 윤리위원회와는 별개의 기구로, 통계학를 포함한 관련 전문 분야의 임상시험
전문가를 포함한다.
시험의뢰자측 대표가 독립 모니터링 위원회에 소속되어 있다면 위원회의 표준
작업지침에 이들의 역할을 명확히(예를 들어, 주요 논제에 대한 투표권 여부 등)
정의한다. 의뢰자측 사람이 눈가림이 해제된 정보에 접근할 수 있기 때문에
의뢰기관 내에서 중간분석 결과의 노출을 통제하는 절차를 마련한다.

