# 안전성과 내약성 평가 {#safety}

## 평가 범위
모든 임상시험에서 안전성과 내약성(용어해설 참조)에 대한 평가는 중요한 요소
이다. 대부분 초기단계에서는 탐색적 성격을 띠고 독성 발현여부에 주로 관심을
두지만, 후기단계에는 보다 많은 임상시험대상자를 대상으로 약물에 대한 안전성과
내약성을 확립한다. 후기단계의 비교시험은 일반적으로 새로운 잠재적인 유해효과를
비뚤리지 않는 방법으로 탐색하는 중요한 방법인데, 이러한 임상시험으로 새로운
유해효과를 밝히는데 검정력이 낮을 수도 있다.
안전성과 내약성에 대한 우월성 및 동등성 평가를 위한 시험계획을 유사약물이나
임상시험약의 다른 용량과 비교함으로써 수행할 수 있다. 이러한 경우에는 안전성
평가를 위한 확증시험에서 얻어진 관련정보에 근거를 둔다.

## 평가변수의 선택과 자료수집
임상시험에서 약물의 안전성과 내약성을 평가하기 위하여 선택된 방법과
측정치들은 관련약물의 유해효과, 전임상시험 및 초기단계 임상시험으로부터 얻은
정보, 특정 약물의 약력학/약동학적 특성에 의해 발생 가능한 결과, 투여경로,
임상시험대상자의 특성, 임상시험 기간 등을 포함한 많은 요인들에 의하여 영향을
받는다. 임상화학 및 혈액학적 실험실적 검사, 활력징후, 그리고 질병, 징후,
증상과 같은 임상적인 이상반응들이 안전성/내약성의 주 자료이다. 심각한 이상
반응이 발생하거나 이상반응으로 인하여 치료를 중단한 경우에는 이상반응 증례를
등록한다(ICH E2A와 ICH E3참조).
서로 다른 임상시험으로부터 얻은 자료의 용이한 통합을 위하여 임상시험
시행중에는 일관된 자료 수집과 평가 방법을 이용한다. 특히 공통된 이상반응
사전을 이용하는 것이 중요하며, 이상반응 사전에는 이상반응 자료를 전신-기관
분류, 권장용어 분류, 유사용어 분류(용어해설 참조) 등 3 가지로 구분하여 요약
하고 있다. 권장용어는 이상반응을 요약하는 차원의 용어이며, 동일 전신-기관
분류에 해당하는 권장용어는 자료의 기술적 보고시 함께 보고될 수 있다(ICH
M1참조).

## 평가대상 임상시험대상자군 및 자료보고
전반적인 안전성 및 내약성 평가를 위한 임상시험대상자군은 일반적으로 적어도
1회 이상 임상시험약을 투여 받은 임상시험대상자들을 의미한다. 안전성 및
내약성에 대한 변수는 임상시험대상자로부터 이상반응의 형태, 심각성의 정도,
발현시점 및 기간을 포함하여 가능한 한 포괄적으로 수집한다(ICH E2B참조).
여성이나 고령자(ICH E7 참조), 중환자, 병용약물을 투여 받는 사람과 같은 특정
소집단은 안전성과 내약성에 대한 추가적인 평가를 필요로 하며, 이와 같은
평가를 위하여 특수대상을 위한 임상시험 가이드라인을 참조 한다(ICH E3 참조).
모든 안전성 및 내약성 변수는 평가 시 주의를 요하고, 임상시험계획서에
폭넓은 접근방법을 제시한다. 모든 이상반응은 치료 내용과의 관련성 여부에
관계없이 보고되어야 하며, 임상시험대상자로 부터 얻어진 모든 자료는 평가 시
설명되어야 한다. 임상검사 변수의 측정단위와 참고치의 범위에 대하여 신중하게
정의 한다. 만일 동일한 임상시험이지만 여러 임상병리실을 이용하여 실험실적
측정을 하는 경우에는 단일화된 평가를 실시할 수 있도록 임상실험실간의 다른
측정치와 참고치 범위를 표준화한다. 독성에 대한 평가 기준 역시 임상시험계획서에
미리 구체화되고 정당화한다.
이상반응의 발생률은 보통 위험에 처한 임상시험대상자 수에 대한 이상반응
발생 임상시험대상자 수의 분율로 표현한다. 이러한 평가방법이 언제나 명확한 것은
아니며, 예를 들어 상황에 따라 임상시험대상자 수나 노출의 정도(예: 임상시험
대상자-년수)가 분모로 사용되기도 한다. 발생률 계산의 목적이 위험성을 추정하는
것이든 처치군간의 비교를 행하는 것이든 간에 임상시험계획서 안에 정의하는
것은 중요하다. 장기간의 임상시험을 계획하여, 임상시험의 조기종료 혹은 사망에
대한 실질적인 분율을 예상하는데 특히 중요하다. 위험성을 과소평가하지 않기
위하여 생존분석법을 고려하여야 하고 이상반응의 누적발생률을 산출한다.
임상시험대상자의 질병에 따라 징후나 증상의 발생수준을 무시할 수 없는 경우
(예: 정신과 임상시험)에는 여러 다른 종류의 이상반응에 대한 위험도를 추정할 때
이를 고려한다. 처리방법으로는 1) 치료전 기초자료와 비교하여 이상반응이 새로이
발생하거나 악화된 경우에만 이상반응을 보고한다는 ‘치료 중 발생한 이상반응
(용어설명 참조)’ 개념을 이용하거나, 2) 임상시험대상자의 기저상태의 징후나
증상의 영향을 감소시키기 위하여, 경도의 이상반응은 무시하거나 반복 방문 시에
관찰되는 경우에만 이상반응을 포함시키는 원칙을 정하는 방법도 적절할 수 있다.
이런 방법들은 임상시험계획서에 설명하고 정당화 한다.

## 통계적 평가
안전성 및 내약성에 대한 연구는 다차원적인 문제이다. 약물의 몇몇 유해효과는
보통 예상이 가능하고 특별히 모니터 되지만, 발생 가능한 유해효과의 범위는
매우 넓고 예상치 못했던 새로운 효과도 항상 발생 가능하다. 더욱이 병용금지
약제의 사용과 같은 임상시험계획서 위반에서 오는 이상반응은 비뚤림을 일으킬 수도
있다. 이런 배경으로 볼 때, 약물의 안전성 및 내약성에 대한 통계적 분석 및 평가는
매우 어렵고, 따라서 확증시험으로부터 안전성 및 내약성에 관한 확정적 정보를
얻는다는 것은 일상적이라기보다는 예외에 가깝다.
안전성 및 내약성에 대한 자료는 해석을 용이하게 하기 위해 주로 신뢰구간을
함께 보고할 수 있다. 또한 치료 군별 및 임상시험대상자별 이상반응의 형태를
그래프 형태로 보고하는 것이 유용하다.
연구대상인 주요 이상반응의 차이에 대한 평가를 가능하도록 하거나 안전성
및 내약성 변수들 중 추가적인 주의를 기울여야 할 필요가 있는 차이를 강조하기
위하여 p-값의 계산이 유용할 수 있다. 특히 적절한 방법으로 요약하기 어려운
임상검사치의 경우 유용하다. 임상검사치는 평균치를 비교하는 정량적 분석이나
역치를 기준으로 한 범주형 자료를 대상으로 하는 정성적 분석법의 사용이 권장
된다.
가설검정시 다중성을 고려하여 제 1종 오류를 조절하지만 일반적으로 안전성
평가시 제 2종 오류가 더 큰 관심사이다. 다중성을 보정하지 않는 경우에는
통계적으로 유의한 발견을 하더라도 해석에 매우 주의를 기울인다.
대부분의 연구에서 연구자들은 시험약이 대조약물 및 위약과 비교하여 안전성 및
내약성에 있어서 임상적으로 허용할 수 없는 차이가 없다는 것을 입증하려 한다.
유효성의 비열등성 평가시험 및 동등성 평가시험에서와 마찬가지로 신뢰구간을
이용하는 것이 가설검정보다 선호된다. 이러한 방법으로, 발현빈도가 낮아서
정밀도가 상당히 떨어지는 것을 명확하게 설명한다.

## 통합 요약
일반적으로 임상시험용의약품 개발 기간 동안 수행된 일련의 임상시험으로부터
얻어진 자료로 의약품의 안전성을 요약하거나, 특히 품목허가를 받기 위하여
자료를 제출할 때 의약품의 안전성 및 내약성에 관한 자료를 요약하게 된다.
이러한 요약된 자료의 유용성은 자료의 품질 수준이 높고 각각의 임상시험이
적절히 잘 통제되었느냐에 좌우된다.
비록 일반적으로 임상시험 전체를 요약하여 위해성/유익성 평가를 수행하지만,
의약품의 전반적 유용성은 항상 위해성/유익성 사이의 균형의 문제이고, 단일
연구에서도 이러한 점을 깊이 고려한다(7.2.2절 참조).

