# 보고 {#report}

## 평가 및 보고
임상시험계획서에 분석의 주요 원칙을 명시한다. 임상시험 종료 후 각종 자료가
모아지고 예비 검토될 때, 계획된 분석법을 눈가림 상태에서 재검토하는 것이
권장된다. 치료에 대하여 눈가림한 상태에서 분석 전 재검토 시 고려할 사항은 :
1) 분석대상으로부터 일부 자료나 임상시험대상자의 제외 2) 자료변환의 가능성
3) 이상치의 정의 4) 최근 다른 연구에서 밝혀진 중요한 공변량의 분석모델 추가
5) 모수적 또는 비모수적 방법의 사용 등이다. 결정사항은 보고서에 명시하고,
눈가림 상태에서 내린 결정은 비뚤림을 최소화하기 때문에 통계학자들이 무작위
배정 코드를 알고 난 후에 얻어진 결론과는 구분한다. 눈가림이 아닌 상태에서
중간분석에 참여한 통계학자 등은 눈가림 재검토나 통계분석 계획의 조정에
참여하지 않는다. 치료효과가 자료상 명확히 드러나서 눈가림이 제대로 이행되지
못하는 경우 눈가림 재검토에도 통계학자나 관련자는 직접 관여하지 않는다.
자료보고 및 표 등 자세한 사항은 눈가림 재검토 시 완료되어 실제 분석 시에는
임상시험대상자 선정, 자료 선택 및 수정, 자료 요약 및 도표화, 추정 및 가설
검정을 포함한 모든 분석계획을 마련한다. 일단 자료의 타당성에 대한 검토가
완료되면, 미리 정해진 계획에 따라 분석을 수행한다. 이러한 분석이 사전에
작성된 계획에 충실하면 할수록 결과에 대한 신뢰성은 높아진다. 임상시험(변경)
계획서, 또는 자료의 눈가림 재검토에 근거한 통계분석법과 실제로 수행한 분석법에
차이가 있는 경우에는 특별한 주의를 기울인다. 계획된 분석법으로부터 벗어난
내용에 대해서는 보다 구체적인 설명을 한다.
시험에 참가한 모든 임상시험대상자는 분석대상에 포함되었는지 여부에 관계없이
보고서에 설명한다. 또한 분석에서 제외된 모든 이유에 대해서도 문서화한다. ;
배정된 대로 분석 군에는 포함되었으나 계획서 순응 임상시험대상자군에서 제외된
임상시험대상자 및 그 제외사유에 대하여도 언급한다. 유사하게, 분석에 포함된
모든 임상시험대상자에 대한 관련 시점에서의 모든 중요한 변수 측정값에 대하여
설명한다.
임상시험대상자 및 자료의 결측, 투여중지 및 임상시험계획 위반이 주 변수의
주요 분석에 미치는 영향에 대하여 신중하게 고려한다. 추적관찰 실패나 치료중지
또는 중대한 임상시험계획서 위반이 있었던 증례에 대하여 명시하고, 그 사유
및 치료, 결과와의 상관성을 포함한 기술적 분석결과를 포함한다.
기술적 통계는 임상시험 보고서를 구성하는 필수 불가결한 부분이다. 적절한
표와 그래프를 사용하여 주 변수 및 2차 변수, 핵심 예후인자와 인구통계학적
변수의 중요한 특성 등에 대하여 명백하게 기술한다. 임상시험의 목적과 관련한
주 분석 결과는 특히 세심하게 기술한다. 유의성 검정결과는 임계값에 대한
대소의 표시보다는 정확한 p-값(예, p=0.034)으로 보고한다.
임상시험의 주요 목적으로 제시된 가설에 대한 해답을 제시하는 것이 임상시험
분석의 주목표이기는 하지만, 눈가림 해제 후 분석결과를 근거하여 새로운 가설이
제기되기도 한다. 이러한 경우에 추가적으로 보다 복잡한 통계분석을 적용할
필요가 있으며 계획서에 예정된 분석결과와 분명히 구별하여 그 결과를 보고서에
제시한다.
분석계획 중 공변량으로서 미리 계획되지 않았으나 몇몇 예후적 중요성을 지닌
기저치 측면에서 치료군간 보이지 않는 불균형이 발생할 수 있다. 불균형을
고려한 추가 분석 결과가 미리 계획된 분석법에 의한 결과와 동일하다는 것을
보여줌으로써 이러한 문제를 해결할 수 있다. 만약 그렇지 않다면 불균형이
결론에 미치는 영향에 대하여 검토한다.
일반적으로 사전에 계획되지 않았던 분석은 최소한으로 한다. 주로 치료효과가
몇몇 다른 요인들에 의하여 다양한 경우에 사전에 계획되지 않았던 분석을 한다.
효과가 특히 좋게 나타난 임상시험대상자 세부집단을 확인하기 위하여 시도될
수 있다. 계획되지 않은 세부집단 분석 결과에 대한 과도한 해석의 위험성은 잘
알려져 있으며(5.7절 참조), 이는 되도록 피한다. 임상시험대상자 세부집단에서
치료효과나 유해성이 없는 경우에도 이와 유사한 과도한 해석 문제가 발생할 수
있으므로, 그러한 가능성은 적절히 평가하고 보고한다.
임상시험 결과의 분석, 해석 및 적절한 결과 제시를 통하여 최종적으로 통계적
판단을 한다. 이를 위하여 임상통계학자는 임상시험보고서에 대하여 책임을 지는
연구진의 일원으로 하고, 최종 보고서를 검토하여 승인하는 업무를 맡는다.

## 임상 데이터베이스의 요약
품목허가 신청 시 신약개발 과정 중에 수행된 임상시험을 통하여 보고된 모든
유효성 및 안전성 정보에 대한 전반적 요약 및 종합이 필요하다. 또한 필요한
경우, 연구결과들의 통계적 종합과정을 수반할 수 있다.
요약하는 과정에서 많은 특수한 통계적 관심이 있을 수 있다 : 1) 임상시험
수행과정 동안 처치된 군별 인구통계학적 및 임상적 특성의 기술 2) 관련 임상
비교시험의 결과를 검토하여 유효성에 대한 주 가설을 보강하거나 상쇄되는
정도의 파악 3) 품목허가에 영향을 미치는 잠재적 안전성 문제를 확인하는 모든
임상시험의 통합된 데이터베이스로부터 이용 가능한 안전성 정보의 요약과 발생
가능한 안전성 문제의 확인 등이다. 임상시험 설계 시 일련의 임상시험 특히 그
결과를 통합할 가능성이 있는 임상시험에서는 일관된 정의를 사용하고, 자료를
수집하여, 결과 분석 및 해석이 용이하도록 한다. 약물치료, 병력, 이상반응을
상세히 기록에는 공통된 사전을 사용한다. 주변수 및 이차변수에 대한 공통된
정의는 항상 중요하며, 메타분석(용어해설 참조)에도 필수적이다. 핵심 유효성
변수를 측정하고, 무작위화/등록과 관련된 평가 시점을 조정하고, 임상시험계획서
위반 및 탈락 시험대상자의 처리 및 예후 요소를 정의하는 방식은 특별한 사유가
없는 한 시험기간 동안 일정하게 유지한다.
여러 임상시험의 자료통합을 위하여 사용된 통계적 과정은 상세히 기술한다.
분석에 포함되는 임상시험의 선택과 관련되는 비뚤림의 가능성, 임상시험결과의
동질성, 다양한 변동요인에 대한 적절한 모델화에 주의를 기울인다. 가정 및
임상시험의 선택에 대한 결론의 민감성을 파악한다.

### 유효성 자료(Efficacy Data)
개별 임상시험은 목적을 충족시킬 만큼 임상시험대상자 수가 충분하여야 한다.
필수적으로 핵심 유효성 질문을 제시하는 일련의 임상시험을 요약하여 추가적인
변수에 관한 정보를 얻을 수 있다. 일련의 시험에서 얻은 주 결과는 보통 추정
및 신뢰구간에 주안점을 둔 표와 그래프를 사용하여 비교 가능한 동일한 형식으로
제시한다. 종종 이러한 추정을 결합하는 메타분석이 유용한데, 치료효과의 크기에
대하여 보다 정밀한 추정을 가능하게 하고, 임상시험의 결과에 대한 완전하고
간략한 보고가 가능하기 때문이다. 예외적인 경우에 메타분석은 전체적인 가설
검정을 통해 유효성에 대한 충분한 근거를 제공하는 가장 최선 또는 유일한
방법일 수 있다. 이러한 목적을 위하여 메타분석을 이용하고자 할 때는 메타분석
자체를 수행하기 위한 전향적인 임상시험계획서를 작성한다.

### 안전성 자료(Safety Data)
안전성 자료 요약 시 잠재적인 유해성의 모든 징후를 찾기 위하여 철저히
안전성 데이터베이스를 조사하고, 관찰 결과를 지지할 수 있는 징후를 찾기
위하여 추적 관찰하는 것이 중요하다. 의약품에 노출된 인체로부터 발생한 안전성
자료의 조합은 모든 임상시험대상자의 통합된 안전성 자료를 통합하여 연구대상수가
많아지므로 희귀한 이상반응을 발견할 확률이 높아지며 발생률도 근사적으로
추정할 수 있게 된다. 그러나 이러한 데이터베이스로부터 추정된 발생률은 대조군이
없기 때문에 적절한 평가가 어려우므로, 비교시험으로부터 얻은 데이터가 유용할
수 있다. 동일한 대조약(위약 또는 특정 치료효과가 있는 대조약)을 사용한 여러
시험의 결과들은 통합되거나 각 대조약별로 구분하여 보고한다.
자료조사 후 잠재적인 유해성의 모든 징후도 보고한다. 이러한 잠재적인 유해
효과의 실상에 대한 평가는 수많은 비교로 인한 다중성 문제를 고려한다. 이상반응
발생률과 노출 및 추적기간과의 가능한 관련성을 밝히기 위해 생존분석을 적절히
사용한다. 확인된 유해효과와 관련된 위험도는 적절한 위험/편익 평가가 가능하도록
정량화 한다




